




to handle GetInfo
To GetInfo
	Click "historyNew"
	TypeText "abcd"
	DoubleClick "history.png"
	
End GetInfo
end GetInfo
----------------------------------------------------------------------

To GreetTheUser
	Put ("Welcome to SDET")
End GreetTheUser




gurdianLogInPage.GurdianPage qa
gurdianLogInPage.verifyMenuItems



gurdianLogInPage.GurdianPage qa
Administration.administrationSubMenu
Administration.warningPurgeProduction
Administration.purgeProductionLogIn sa,cactus#1